default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  encoding: unicode
  timeout: 5000
  database: nfctoys

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  